print ('Day 2')
print ('+, -, *, /, **, //, %')
print ()
print ('type 1st number')
num1 = input ()
print ('type 2nd number')
num2 = input ()
print ()
print ('sum =' , int(num1) + int(num2))
print ('difference =' , int(num1) - int(num2))
print ()
print ('product =' , int(num1) * int(num2))
print ('division =' , int(num1) / int(num2))
print ()
print ('quotient =' , int(num1) // int(num2))
print ('remainder =' , int(num1) % int(num2))
print ()
print ('raise to the powe =' , int(num1) ** int(num2))
print ()
print ('Day 3')