print ('Day 8')
print ('lists and tuples')
print ()
print ('make a list of 3 things (press enter after every word)')
inp1 = input()
inp2 = input()
inp3 = input()
fruits = [inp1, inp2, inp3]
print (fruits)
print ()
inp4 = input('Enter 1 more item: ')
fruits.append(inp4)
print (fruits)
print ()
num1 = int(input('Type the item number which you want to view: ')) - 1
print(fruits[num1])
print()
num2 = int(input('type the item number which you want to replace: ')) - 1
inp5 = input('Enter the item which you want to replace: ')
fruits[num2] = inp5
print (fruits)
print()
print ('Your final list is: ')
for x in fruits:
	print (x)
y = len(fruits)
print ('the total items in the list are: ', y)
print ()
position = (240, 528, 'hello')
colour = (255,255,255)
print(type(position))
print(type(colour))
print()
print ('Day 9')