print ('Day 10')
print ('.strip(), len(), .lower(), .upper(), .split()')
print ()
print('Enter words with random spaces and mixed upper and lower cases')
inp1 = input()
inp1a = inp1.strip()
print('Word withour spaces in starting and end:', inp1a)
print('Word in all upper case:' , inp1a.upper())
print('Word in all lower case:' , inp1a.lower())
print('No. of leters in the word =', len(inp1a))
print()
inp2 = input('Write different word sperared by a letter or sumbol (U can even use spacebar):')
inp3 = input('Write the letter or symbol which u chose:')
print()
print('the different words are:')
for x in inp2.split(inp3):
	print(x)
print()
print('Day 11')