print('Day 14')
print('Writing .txt file')
print()
txt1 = open('Writing file.txt', 'w')
print('Write what you want to write in text file:')
inp1 = input()
txt1.write(inp1)
txt1.close()
print()
print('Day 15')